# Generated by Django 5.0.6 on 2024-11-02 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_now', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating should be between 0.0 and 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/deals/')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='static/featured/')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/flash_sales/')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('channels', models.CharField(max_length=255)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('arts-crafts-intl-ship', 'Arts & Crafts'), ('automotive-intl-ship', 'Automotive'), ('baby-products-intl-ship', 'Baby'), ('beauty-intl-ship', 'Beauty & Personal Care'), ('books-intl-ship', 'Books'), ('electronics-intl-ship', 'Computers & Electronics'), ('digital-music-intl-ship', 'Digital Music'), ('fashion-female-intl-ship', "Female's Fashion"), ('gift-card-intl-ship', 'Gift Card'), ('health-intl-ship', 'Health & Household'), ('kitchen-intl-ship', 'Home & Kitchen'), ('industrial-intl-ship', 'Industrial & Scientific'), ('fashion-male-intl-ship', "Male's Fashion"), ('movies-tv-intl-ship', 'Movies, Games & Music'), ('software-intl-ship', 'Software'), ('sporting-intl-ship', 'Sports & Outdoors'), ('tools-intl-ship', 'Tools & Improvement')], max_length=50)),
                ('product_type', models.CharField(choices=[('arts-crafts-intl-ship', 'Arts & Crafts'), ('automotive-intl-ship', 'Automotive'), ('baby-products-intl-ship', 'Baby'), ('beauty-intl-ship', 'Beauty & Personal Care'), ('books-intl-ship', 'Books'), ('electronics-intl-ship', 'Computers & Electronics'), ('digital-music-intl-ship', 'Digital Music'), ('fashion-female-intl-ship', "Female's Fashion"), ('gift-card-intl-ship', 'Gift Card'), ('health-intl-ship', 'Health & Household'), ('kitchen-intl-ship', 'Home & Kitchen'), ('industrial-intl-ship', 'Industrial & Scientific'), ('fashion-male-intl-ship', "Male's Fashion"), ('movies-tv-intl-ship', 'Movies, Games & Music'), ('software-intl-ship', 'Software'), ('sporting-intl-ship', 'Sports & Outdoors'), ('tools-intl-ship', 'Tools & Improvement')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='static/trend/')),
                ('category', models.CharField(choices=[('headphones', 'Headphones'), ('mens-watches', "Men's Watches"), ('best-laptops', 'Best Laptops'), ('digital-cameras', 'Digital Cameras'), ('wireless-controllers', 'Wireless Controadmin.site.register(Collection)llers')], max_length=50)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
