# Generated by Django 5.0.6 on 2024-08-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_discountoffer_slideshowimage_collectionpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountoffer',
            name='title',
        ),
    ]
